### ISSUE TITLE
module request: inverted switch n:1

### ISSUE THREAD

**Issue by glocke01** [23volts/23volts-vcv#2]
I'd like to have a module that combined the functionality of a 1 to N switch with a merge. This would be very useful for programmatically creating notes. 

As with a normal sequential switch, all outputs would be muted but the selected one, and a trigger input would advance the selection. 

![sequential_switch_note_scheduler](https://user-images.githubusercontent.com/12255580/68972333-8fbb9180-07b9-11ea-9d10-7ef68c0c3f3f.png)
An example application is shown here, where the functionality I'd like is reproduced by the ML sequential switch and the VCV Merge; it would be a bit of work to set this up to have 16 channels. 

What's happening here: dust makes triggers. (The Chance module reduces the number of triggers.)  These triggers advance the switch, and they are the input to the switch. Thus, every new trigger is sent to a different output of the switch. The 8 outputs of the switch are then sent to a merge. After the merge, each trigger acts as a note-on. Thus, each trigger goes to the next poly channel, allowing the notes to sustain and overlap.

Probably most people would rather use a trigger sequencer than dust, but I like ambient.

**Comment by RemiCollin** [comment]
That's interesting. I planned to make a Switch 1:N at first, but couldn't find a use case for it. You just provided one, so I guess I'll implement it finally  :)

**Comment by glocke01** [comment]
that would be awesome, thanks!!
