### ISSUE TITLE
Ideas for a SwitchN1XL module

### ISSUE THREAD

**Issue by vcvrackideas** [23volts/23volts-vcv#20]
Ok, it seems to me Switch N1 became my favorite arpeggiator in VCV Rack! No more shaman dancing - just put poly cable and mangle the switch in any direction you like, thanks that's awesome module! Just one thing I really missed is the lack of gate\trigger output to complete the arp mission. But it seems to me you wanted to make it a tiny one and... what do you think about an expander for example>

**Comment by RemiCollin** [comment]
I'm thinking about making a bigger version with more features in a new module, SwitchN1XL or someting like that, as the current layout is very crowded indeed.

About the functionnality itself, it should output a trig/gate when any of the trig input (minus the reset) is activated, right ?

**Comment by vcvrackideas** [comment]
> About the functionnality itself, it should output a trig/gate when any of the trig input (minus the reset) is activated, right ?

Yep, output should follow the red dot so in that way we get synced 1v\oct and gates in the case of using it as the arp. Thank you!

**Comment by RemiCollin** [comment]
Ok! Feel free if you have another idea for an XL module. For now i'm thinking of having 2 poly inputs A/B which can be switched to the main output, as well as logic outputs (SUM, MIN, MAX).

**Comment by RemiCollin** [comment]
New module SwitchN2 was added in 1.2.0
