### ISSUE TITLE
Poly Merge doesn't really work.

### ISSUE THREAD

**Issue by Chaircrusher** [23volts/23volts-vcv#23]
I tried using poly merge to merge the CV & Gate of two different sequencers.  I could tell by ear that something was screwy, but this image illustrates the issue:

I send a constant 1, 2, 3, 4 to one VCV Merge, and 5, 6, 7, 8 to a second VCV Merge.  When I plug the two poly signals into a VCV Scope, you see what is expected: 8 constant lines one volt apart.

I use Poly Merge to merge the two poly signals, and you can see from the scope that there's something wrong,  The first 2 signals from each of the VCV Merge seem to be passed through, but the other 4 signals come through as zero.
![image](https://user-images.githubusercontent.com/482621/74573062-b4084500-4f45-11ea-95c8-d83bc256b3da.png)

**Comment by RemiCollin** [comment]
Hello, thanks for reporting this.. I could reproduce it seems there's something happening when changing number of channels when poly cables are already connected. Will fix this

**Comment by RemiCollin** [comment]
Fixed in 1.1.5 version. I submit to the library, If you'd like to try it before you can use the builds available in last release ;)
