### ISSUE TITLE
Unusual results from Polymerge

### ISSUE THREAD

**Issue by xandramax** [23volts/23volts-vcv#24]
Polymerge does not seem to be functioning correctly:
![2](https://user-images.githubusercontent.com/12039110/74620381-f88f0e80-5106-11ea-94cc-0709d532e34c.PNG)
![3](https://user-images.githubusercontent.com/12039110/74620384-fb89ff00-5106-11ea-9f68-0c948ff6092b.PNG)
![4](https://user-images.githubusercontent.com/12039110/74620388-fd53c280-5106-11ea-82a5-b712d7546717.PNG)

**Comment by RemiCollin** [comment]
Hello, same issue as this : https://github.com/23volts/23volts-vcv/issues/23 ?
