### ISSUE TITLE
Modules make Rack v2 crash on exit.

### ISSUE THREAD

**Issue by jpnielsen** [23volts/23volts-vcv#37]
On windows 11, Rack-2.git.042a9ce0

23volts modules that makes Rack crash on exit:

Multimap Knobs
Multimap Buttons
S8
S4
M4
Switch N:1
Clock M8
PolyMerge
PolySplit
MonoPoly

23volts modules that does not make Rack crash on exit:

Mem
Morph
Cells
MIDI-PC

The crash error messages says to look in the log file, but there's nothing related to the crash there.
[log.txt](https://github.com/23volts/23volts-vcv/files/7348600/log.txt)

**Comment by RemiCollin** [comment]
Thanks for reporting this. It was an issue on the polyphonic port which is shared for this module. Just fixed it ;)
